"""Centralized configuration defaults and environment variable names."""
IBKR_HOST_ENV = "IBKR_HOST"
IBKR_PORT_ENV = "IBKR_PORT"
IBKR_CLIENT_ID_ENV = "IBKR_CLIENT_ID"

REDIS_URL_ENV = "REDIS_URL"
REDIS_PASSWORD_ENV = "REDIS_PASSWORD"

QUESTDB_HOST_ENV = "QUESTDB_HOST"
QUESTDB_PORT_ENV = "QUESTDB_PORT"
QUESTDB_USER_ENV = "QUESTDB_USER"
QUESTDB_PASSWORD_ENV = "QUESTDB_PASSWORD"
QUESTDB_DATABASE_ENV = "QUESTDB_DATABASE"

MYSQL_HOST_ENV = "MYSQL_HOST"
MYSQL_PORT_ENV = "MYSQL_PORT"
MYSQL_USER_ENV = "MYSQL_USER"
MYSQL_PASSWORD_ENV = "MYSQL_PASSWORD"
MYSQL_DATABASE_ENV = "MYSQL_DATABASE"

INDEX_SYNC_INTERVAL_SECONDS_ENV = "INDEX_SYNC_INTERVAL_SECONDS"
IBKR_MARKET_DATA_LINES_ENV = "IBKR_MARKET_DATA_LINES"
INDEX_COMPOSITION_PROVIDER_ENV = "INDEX_COMPOSITION_PROVIDER"
IBKR_REST_APP_NAME_ENV = "IBKR_REST_APP_NAME"
IBKR_REST_CONNECT_ON_STARTUP_ENV = "IBKR_REST_CONNECT_ON_STARTUP"
IBKR_REST_MARKET_DATA_TTL_SECONDS_ENV = "IBKR_REST_MARKET_DATA_TTL_SECONDS"
IBKR_REST_MARKET_DATA_CACHE_MAXSIZE_ENV = "IBKR_REST_MARKET_DATA_CACHE_MAXSIZE"

DEFAULT_IBKR_HOST = "127.0.0.1"
DEFAULT_IBKR_PORT = 4001
DEFAULT_IBKR_CLIENT_ID = 1

DEFAULT_REDIS_URL = "redis://18.180.162.113:6379/0"
DEFAULT_REDIS_PASSWORD = "96854233"

DEFAULT_QUESTDB_HOST = "127.0.0.1"
DEFAULT_QUESTDB_PORT = 8812
DEFAULT_QUESTDB_USER = "admin"
DEFAULT_QUESTDB_PASSWORD = "96854233"
DEFAULT_QUESTDB_DATABASE = "qdb"

DEFAULT_MYSQL_HOST = "127.0.0.1"
DEFAULT_MYSQL_PORT = 3306
DEFAULT_MYSQL_USER = "root"
DEFAULT_MYSQL_PASSWORD = ""
DEFAULT_MYSQL_DATABASE = "trading"
DEFAULT_MYSQL_POOL_MIN_SIZE = 2
DEFAULT_MYSQL_POOL_MAX_SIZE = 10

DEFAULT_INDEX_SYNC_INTERVAL_SECONDS = 86_400
DEFAULT_IBKR_MARKET_DATA_LINES = 100
DEFAULT_INDEX_COMPOSITION_PROVIDER = ""
DEFAULT_IBKR_REST_APP_NAME = "IBKRRestApp"
DEFAULT_IBKR_REST_CONNECT_ON_STARTUP = False
DEFAULT_IBKR_REST_MARKET_DATA_TTL_SECONDS = 5.0
DEFAULT_IBKR_REST_MARKET_DATA_CACHE_MAXSIZE = 512

# Default G10 equity index reload universe:
# US, Canada, UK, Germany, France, Italy, Japan, Netherlands, Belgium, Sweden, Switzerland.
DEFAULT_G10_INDEX_SYMBOLS_BY_COUNTRY = {
    "US": "SPX",
    "Canada": "TSX",
    "UK": "FTSE100",
    "Germany": "DAX",
    "France": "CAC40",
    "Italy": "FTSEMIB",
    "Japan": "NIKKEI225",
    "Netherlands": "AEX",
    "Belgium": "BEL20",
    "Sweden": "OMXS30",
    "Switzerland": "SMI",
}
DEFAULT_G10_INDEX_SYMBOLS = tuple(DEFAULT_G10_INDEX_SYMBOLS_BY_COUNTRY.values())

IBKR_API_REQUESTS_PER_SECOND_DIVISOR = 2
IBKR_HISTORICAL_REQUEST_WINDOW_SECONDS = 600
IBKR_HISTORICAL_MAX_REQUESTS_PER_WINDOW = 60
IBKR_HISTORICAL_IDENTICAL_REQUEST_COOLDOWN_SECONDS = 15
IBKR_HISTORICAL_SAME_CONTRACT_WINDOW_SECONDS = 2
IBKR_HISTORICAL_SAME_CONTRACT_MAX_REQUESTS = 5
IBKR_CONSERVATIVE_HISTORICAL_CONCURRENCY = 8

MARKET_OHLCV_TABLE = "market_ohlcv"
REDIS_LATEST_BAR_KEY_TEMPLATE = "MarketData::{asset_class}::{bar_size}:latest"
REDIS_SYMBOL_LATEST_BAR_KEY_TEMPLATE = "MarketData::{asset_class}::{symbol}::{bar_size}:latest"
REDIS_INDEX_COMPOSITION_KEY_TEMPLATE = "GlobalIndex:{index_symbol}:composition"
REDIS_SCHEDULER_JOB_KEY_TEMPLATE = "SchedulerJob::{job_name}"
REDIS_SCHEDULER_JOB_SCAN_PATTERN = "SchedulerJob::*"
REDIS_IBKR_RATE_LIMIT_PREFIX = "IBKRRateLimit:historical"
