"""Centralized configuration defaults and environment variable names."""
IBKR_HOST_ENV = "IBKR_HOST"
IBKR_PORT_ENV = "IBKR_PORT"
IBKR_CLIENT_ID_ENV = "IBKR_CLIENT_ID"

REDIS_URL_ENV = "REDIS_URL"
REDIS_PASSWORD_ENV = "REDIS_PASSWORD"
IBKR_REST_BASE_URL_ENV = "IBKR_REST_BASE_URL"

QUESTDB_HOST_ENV = "QUESTDB_HOST"
QUESTDB_PORT_ENV = "QUESTDB_PORT"
QUESTDB_WRITE_PORT_ENV = "QUESTDB_WRITE_PORT"
QUESTDB_USER_ENV = "QUESTDB_USER"
QUESTDB_PASSWORD_ENV = "QUESTDB_PASSWORD"
QUESTDB_DATABASE_ENV = "QUESTDB_DATABASE"

MYSQL_HOST_ENV = "MYSQL_HOST"
MYSQL_PORT_ENV = "MYSQL_PORT"
MYSQL_USER_ENV = "MYSQL_USER"
MYSQL_PASSWORD_ENV = "MYSQL_PASSWORD"
MYSQL_DATABASE_ENV = "MYSQL_DATABASE"
MARKET_DATA_DB_BACKEND_ENV = "MARKET_DATA_DB_BACKEND"

INDEX_SYNC_INTERVAL_SECONDS_ENV = "INDEX_SYNC_INTERVAL_SECONDS"
IBKR_MARKET_DATA_LINES_ENV = "IBKR_MARKET_DATA_LINES"
INDEX_COMPOSITION_PROVIDER_ENV = "INDEX_COMPOSITION_PROVIDER"
FIXED_INCOME_REFERENCE_PROVIDER_ENV = "FIXED_INCOME_REFERENCE_PROVIDER"
TELEGRAM_BOT_TOKEN_ENV = "TELEGRAM_BOT_TOKEN"
TELEGRAM_CHAT_ID_ENV = "TELEGRAM_CHAT_ID"
TELEGRAM_LOG_LEVEL_ENV = "TELEGRAM_LOG_LEVEL"

IBKR_REST_APP_NAME_ENV = "IBKR_REST_APP_NAME"
IBKR_REST_CONNECT_ON_STARTUP_ENV = "IBKR_REST_CONNECT_ON_STARTUP"
IBKR_REST_MARKET_DATA_TTL_SECONDS_ENV = "IBKR_REST_MARKET_DATA_TTL_SECONDS"
IBKR_REST_MARKET_DATA_CACHE_MAXSIZE_ENV = "IBKR_REST_MARKET_DATA_CACHE_MAXSIZE"
IBKR_MARKET_DEPTH_REQUEST_TIMEOUT_SECONDS_ENV = "IBKR_MARKET_DEPTH_REQUEST_TIMEOUT_SECONDS"
IBKR_MARKET_DEPTH_LEASE_WAIT_SECONDS_ENV = "IBKR_MARKET_DEPTH_LEASE_WAIT_SECONDS"
IBKR_MARKET_DEPTH_CACHE_TTL_SECONDS_ENV = "IBKR_MARKET_DEPTH_CACHE_TTL_SECONDS"
IBKR_REST_OHLCV_RATE_LIMIT_RETRY_DELAY_SECONDS_ENV = "IBKR_REST_OHLCV_RATE_LIMIT_RETRY_DELAY_SECONDS"
IBKR_REST_OHLCV_RATE_LIMIT_RETRY_COUNT_ENV = "IBKR_REST_OHLCV_RATE_LIMIT_RETRY_COUNT"
IBKR_EQUITY_SNAPSHOT_WAIT_SECONDS_ENV = "IBKR_EQUITY_SNAPSHOT_WAIT_SECONDS"
IBKR_EQUITY_SNAPSHOT_LEASE_TTL_SECONDS_ENV = "IBKR_EQUITY_SNAPSHOT_LEASE_TTL_SECONDS"
IBKR_HISTORICAL_MAX_CHUNKS_ENV = "IBKR_HISTORICAL_MAX_CHUNKS"
IBPYTHON_LIVE_SMOKE_ENV = "IBPYTHON_LIVE_SMOKE"
IBKR_ORDER_AUTH_REDIS_KEY_ENV = "IBKR_ORDER_AUTH_REDIS_KEY"
IBKR_RATE_LIMIT_ENABLED_ENV = "IBKR_RATE_LIMIT_ENABLED"
IBKR_RATE_LIMIT_GLOBAL_MESSAGES_PER_SECOND_ENV = "IBKR_RATE_LIMIT_GLOBAL_MESSAGES_PER_SECOND"
IBKR_RATE_LIMIT_MARKET_DATA_RESERVE_ENV = "IBKR_RATE_LIMIT_MARKET_DATA_RESERVE"
IBKR_RATE_LIMIT_MARKET_DATA_LEASE_TTL_SECONDS_ENV = "IBKR_RATE_LIMIT_MARKET_DATA_LEASE_TTL_SECONDS"

IBKR_API_BEARER_TOKEN_ENV = "IBKR_API_BEARER_TOKEN"
IBKR_WEB_API_BASE_URL_ENV = "IBKR_WEB_API_BASE_URL"
IBKR_WEB_API_BEARER_TOKEN_ENV = "IBKR_WEB_API_BEARER_TOKEN"
IBKR_WEB_API_COOKIE_ENV = "IBKR_WEB_API_COOKIE"
IBKR_WEB_API_VERIFY_SSL_ENV = "IBKR_WEB_API_VERIFY_SSL"
IBKR_EVENT_CONTRACTS_LIVE_ORDERS_ENABLED_ENV = "IBKR_EVENT_CONTRACTS_LIVE_ORDERS_ENABLED"
MCP_HTTP_HOST_ENV = "MCP_HTTP_HOST"
MCP_HTTP_PORT_ENV = "MCP_HTTP_PORT"
MCP_API_KEY_ENV="***"

APP_VERSION = "0.1.0"

DEFAULT_TELEGRAM_BOT_TOKEN = ""
DEFAULT_TELEGRAM_CHAT_ID = ""
DEFAULT_TELEGRAM_LOG_LEVEL = "WARNING"

DEFAULT_IBKR_HOST = "127.0.0.1"
DEFAULT_IBKR_PORT = 4001
DEFAULT_IBKR_CLIENT_ID = 1

DEFAULT_REDIS_URL = "redis://localhost:6379/0"
DEFAULT_REDIS_PASSWORD = ""
DEFAULT_IBKR_REST_BASE_URL = "http://localhost:8000"

DEFAULT_QUESTDB_HOST = "127.0.0.1"
DEFAULT_QUESTDB_PORT = 8812
DEFAULT_QUESTDB_WRITE_PORT = 9009
DEFAULT_QUESTDB_USER = "admin"
DEFAULT_QUESTDB_PASSWORD = ""
DEFAULT_QUESTDB_DATABASE = "qdb"

DEFAULT_MYSQL_HOST = "127.0.0.1"
DEFAULT_MYSQL_PORT = 3306
DEFAULT_MYSQL_USER = "root"
DEFAULT_MYSQL_PASSWORD = ""
DEFAULT_MYSQL_DATABASE = "trading"
DEFAULT_MYSQL_POOL_MIN_SIZE = 2
DEFAULT_MYSQL_POOL_MAX_SIZE = 10
DEFAULT_MARKET_DATA_DB_BACKEND = "questdb"

DEFAULT_INDEX_SYNC_INTERVAL_SECONDS = 86_400
DEFAULT_IBKR_MARKET_DATA_LINES = 100
DEFAULT_INDEX_COMPOSITION_PROVIDER = ""
DEFAULT_FIXED_INCOME_REFERENCE_PROVIDER = ""
DEFAULT_IBKR_REST_APP_NAME = "IBKRRestApp"
DEFAULT_IBKR_REST_CONNECT_ON_STARTUP = False
DEFAULT_IBKR_REST_MARKET_DATA_TTL_SECONDS = 5.0
DEFAULT_IBKR_REST_MARKET_DATA_CACHE_MAXSIZE = 512
DEFAULT_IBKR_MARKET_DEPTH_REQUEST_TIMEOUT_SECONDS = 5.0
DEFAULT_IBKR_MARKET_DEPTH_LEASE_WAIT_SECONDS = 2.0
DEFAULT_IBKR_MARKET_DEPTH_CACHE_TTL_SECONDS = 0.25
DEFAULT_IBKR_REST_OHLCV_RATE_LIMIT_RETRY_DELAY_SECONDS = 60.0
DEFAULT_IBKR_REST_OHLCV_RATE_LIMIT_RETRY_COUNT = 1
DEFAULT_IBKR_EQUITY_SNAPSHOT_WAIT_SECONDS = 11.5
DEFAULT_IBKR_EQUITY_SNAPSHOT_LEASE_TTL_SECONDS = 30.0
DEFAULT_IBKR_HISTORICAL_MAX_CHUNKS = 60
DEFAULT_IBPYTHON_LIVE_SMOKE = False
DEFAULT_IBKR_ORDER_AUTH_REDIS_KEY = "OrderAuth::bearer_token"
DEFAULT_IBKR_RATE_LIMIT_ENABLED = True
DEFAULT_IBKR_RATE_LIMIT_GLOBAL_MESSAGES_PER_SECOND = 50
DEFAULT_IBKR_RATE_LIMIT_MARKET_DATA_LEASE_TTL_SECONDS = 3600.0

DEFAULT_IBKR_API_BEARER_TOKEN = ""
DEFAULT_IBKR_WEB_API_BASE_URL = "https://localhost:5000/v1/api"
DEFAULT_IBKR_WEB_API_BEARER_TOKEN = ""
DEFAULT_IBKR_WEB_API_COOKIE = ""
DEFAULT_IBKR_WEB_API_VERIFY_SSL = False
DEFAULT_IBKR_EVENT_CONTRACTS_LIVE_ORDERS_ENABLED = False
DEFAULT_MCP_HTTP_HOST = "127.0.0.1"
DEFAULT_MCP_HTTP_PORT = 9000
DEFAULT_MCP_API_KEY = ""

# Default G10 equity index reload universe:
# US, Canada, UK, Germany, France, Italy, Japan, Netherlands, Belgium, Sweden, Switzerland.
DEFAULT_G10_INDEX_SYMBOLS_BY_COUNTRY = {
    "US": "SPX",
    "Canada": "TSX",
    "UK": "FTSE100",
    "Germany": "DAX",
    "France": "CAC40",
    "Italy": "FTSEMIB",
    "Japan": "NIKKEI225",
    "Netherlands": "AEX",
    "Belgium": "BEL20",
    "Sweden": "OMXS30",
    "Switzerland": "SMI",
}
DEFAULT_G10_INDEX_SYMBOLS = tuple(DEFAULT_G10_INDEX_SYMBOLS_BY_COUNTRY.values())

IBKR_API_REQUESTS_PER_SECOND_DIVISOR = 2
IBKR_HISTORICAL_REQUEST_WINDOW_SECONDS = 600
IBKR_HISTORICAL_MAX_REQUESTS_PER_WINDOW = 60
IBKR_HISTORICAL_IDENTICAL_REQUEST_COOLDOWN_SECONDS = 15
IBKR_HISTORICAL_SAME_CONTRACT_WINDOW_SECONDS = 2
IBKR_HISTORICAL_SAME_CONTRACT_MAX_REQUESTS = 5
IBKR_CONSERVATIVE_HISTORICAL_CONCURRENCY = 8

MARKET_OHLCV_TABLE = "market_ohlcv"
QUESTDB_MARKET_OHLCV_TABLE = "EquityOHLCV"
REDIS_LATEST_BAR_KEY_TEMPLATE = "MarketData::{asset_class}::{bar_size}:latest"
REDIS_SYMBOL_LATEST_BAR_KEY_TEMPLATE = "MarketData::{asset_class}::{symbol}::{bar_size}:latest"
REDIS_INDEX_COMPOSITION_KEY_TEMPLATE = "GlobalIndex:{index_symbol}:composition"
REDIS_SCHEDULER_JOB_KEY_TEMPLATE = "SchedulerJob::{job_name}"
REDIS_SCHEDULER_JOB_SCAN_PATTERN = "SchedulerJob::*"
REDIS_SCHEDULER_LEASE_KEY_TEMPLATE = "SchedulerLease::{job_name}"
REDIS_SCHEDULER_RUN_LATEST_KEY_TEMPLATE = "SchedulerRun::{job_name}:latest"
REDIS_SCHEDULER_RUN_HISTORY_KEY_TEMPLATE = "SchedulerRun::{job_name}:history"
REDIS_SCHEDULER_RUN_HISTORY_MAXLEN = 100
REDIS_IBKR_RATE_LIMIT_PREFIX = "IBKRRateLimit:historical"
REDIS_IBKR_APP_RATE_LIMIT_PREFIX = "IBKRRateLimit"
REDIS_OHLCV_SNAPSHOT_LAST_TS_KEY_TEMPLATE = "OhlcvSnapshot::{job_name}::{symbol}::{bar_size}:last_ts"
REDIS_OHLCV_SNAPSHOT_STATUS_KEY_TEMPLATE = "OhlcvSnapshot::{job_name}::{symbol}::{bar_size}:status"
REDIS_OHLCV_SNAPSHOT_CALENDAR_KEY_TEMPLATE = (
    "OhlcvSnapshotCalendar::{asset_class}::{exchange}::{symbol}::{contract_fingerprint}::{date}::{use_rth}:has_session"
)

EQUITY_SNAPSHOT_TABLE = "equity_snapshot"
REDIS_EQUITY_SNAPSHOT_KEY_TEMPLATE = "EquitySnapshot::{symbol}:latest"
FX_OPTION_SNAPSHOT_TABLE = "fx_option_snapshot"
REDIS_FX_OPTION_SNAPSHOT_KEY_TEMPLATE = "FXOptionSnapshot::{contract_key}:latest"
REDIS_SNAPSHOT_WATCHLIST_KEY_TEMPLATE = "SnapshotWatchlist::{name}"
REDIS_ORDER_ENVELOPE_KEY_TEMPLATE = "OrderCache::{order_uuid}"
REDIS_ORDER_ENVELOPE_TTL_SECONDS = 86_400  # 24h default TTL for cached orders
REDIS_ORDER_ENVELOPE_SCAN_PATTERN = "OrderCache::*"
